# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EmbedInTree <- function(x, featureNames, splitFeatures, splits, movements) {
    .Call('_fbboost_EmbedInTree', PACKAGE = 'fbboost', x, featureNames, splitFeatures, splits, movements)
}

